Repository Plaenkler/DDNS-Updater, pull requests merged in 2023-07, with the labels that each got.

#85 [FIX] Server reconstruction
  cmd/main.go
  pkg/server/limiter.go
  pkg/server/middles.go
  pkg/server/service.go
  pkg/server/xrclient.go
Labels: bug, enhancement

#86 [UPD] Super linter v5
  .github/dependabot.yml
  .github/linters/.golangci.yml
  .github/workflows/linters.yml
Labels: dependencies

#87 [ADD] Configuration from environment
  pkg/config/config.go
Labels: enhancement

#91 [FIX] Check if values zero
  pkg/config/config.go
Labels: bug

#90 [UPD] DDNS -> DDNS-Updater
  README.md
  cmd/main.go
  go.mod
  pkg/database/database.go
  pkg/ddns/service.go
  pkg/ddns/update.go
  pkg/server/routes/api/config.go
  pkg/server/routes/api/inputs.go
  pkg/server/routes/api/job.go
  pkg/server/routes/web/index.go
  pkg/server/service.go
Labels: documentation, enhancement

#96 Dependencies
  go.mod
  go.sum
Labels: dependencies

#101 [UPD] Graceful shutdown of the application
  cmd/main.go
Labels: bug, enhancement

#100 [ADD] StopService()
  cmd/main.go
  pkg/server/service.go
Labels: bug, enhancement

#99 [UPD] Restructured database service
  cmd/main.go
  pkg/database/database.go
  pkg/server/routes/api/job.go
  pkg/server/routes/web/index.go
  pkg/server/service.go
Labels: bug, enhancement

#98 [UPD] Segmented service
  cmd/main.go
  pkg/database/database.go
  pkg/ddns/service.go
  pkg/server/routes/api/job.go
  pkg/server/routes/web/index.go
  pkg/server/service.go
Labels: bug, enhancement

#102 Custom logging & graceful shutdown of the application
  cmd/main.go
  pkg/config/config.go
  pkg/database/database.go
  pkg/ddns/resolver.go
  pkg/ddns/service.go
  pkg/logging/logging.go
  pkg/server/routes/api/config.go
  pkg/server/routes/api/job.go
  pkg/server/routes/web/index.go
  pkg/server/service.go
Labels: bug, enhancement

#110 [FIX] Use os.LookupEnv
  pkg/config/config.go
Labels: bug, enhancement

#103 [UPD] Dependencies
  go.mod
  go.sum
Labels: dependencies

#111 [FIX] Lock services
  pkg/database/service.go
  pkg/ddns/service.go
  pkg/server/service.go
Labels: enhancement

#112 [ADD] Multiple resolvers
  pkg/ddns/resolver.go
Labels: enhancement

#113 [FIX] Simplified main
  cmd/main.go
Labels: enhancement

#115 [ADD] Custom resolver
  pkg/config/config.go
  pkg/ddns/resolver.go
  pkg/server/routes/api/config.go
  pkg/server/routes/web/static/html/partials/modals.html
Labels: enhancement

#117 [ADD] Provider NoIP
  pkg/ddns/providers/noip.go
Labels: enhancement

#122 Dependencies
  go.mod
  go.sum
Labels: dependencies

#125 [ADD] SECURITY.md
  SECURITY.md
Labels: documentation, enhancement

#124 [ADD] CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement
